### ISSUE TITLE
EngineerChipFlight missing

### ISSUE THREAD

**Issue by EoD** [CYBUTEK/KerbalEngineer#16]
Version 1.0.14.1

When I am trying to load an old savegame all my ships are being removed to due a missing "EngineerChipFlight". Am I missing something?

**Comment by Kerbas-ad-astra** [comment]
The parts got changed between 0.6 and 1.0.  You can either edit your craft and save files as I did (explained in [this post](http://forum.kerbalspaceprogram.com/threads/18230-0-25-0-90-Kerbal-Engineer-Redux-v0-6-2-12%280-25%29-and-v1-0-14-1%280-90%29/page155?p=1511181#post1511181)), or load up that save with the older version of KER (in whatever version of KSP you were playing before), remove all chips from everything (with e.g. ChopIt), and then bring the save into 0.90.  Make sure you either have an engineer onboard or a Level 3 tracking station in order to see the new readouts.
