### ISSUE TITLE
Very large fuel tanks confuse staging predictions

### ISSUE THREAD

**Issue by roothorick** [CYBUTEK/KerbalEngineer#25]
A stage with a very large fuel tank is not considered distinct from its parent. Here, stage 0 will clearly continue burning after stage 1 is emptied and jettisoned, but KER doesn't think so:

![2015-02-16_00001](https://cloud.githubusercontent.com/assets/6509603/6221984/b0c995f6-b611-11e4-8ad2-b504fefaa8ef.jpg)

It appears to think the center engine will be started alone and its tanks emptied before the side engines are fired, but that's not reflected in the TWR numbers.

The exact same fuel (and dry weight), but this time with X200-32 tanks instead of Jumbo-64s, results in a correct staging prediction and dV calculation:

![2015-02-16_00002](https://cloud.githubusercontent.com/assets/6509603/6222044/b998e65e-b612-11e4-8980-56325138e635.jpg)

**Comment by Gerry1135** [comment]
This is exactly the same problem as is currently being fixed in pull request #24.  When the boosters burn out there is still a small amount of one of the resources in the tank and this is above the threshold at which the simulation considerers the stage empty so it doesn't stage.  Basically, KER is calculating the deltaV as if you don't jettison the boosters once they run out.  The same effect can be seen if you deliberately unbalance the amount of fuel and oxidiser in the X200-32 based boosters (e.g. just drag one of the sliders on one of the booster tanks down a notch).

**Comment by CYBUTEK** [comment]
Tested example craft and is no longer reproducible without manually unbalancing the fuel quantities.
