### ISSUE TITLE
Incorrect torque from parts with PhysicsSignificance=1

### ISSUE THREAD

**Issue by Entropy2016** [CYBUTEK/KerbalEngineer#30]
As of recently, physicsless parts (PhysicsSignificance=1) are not massless anymore, but rather, they [impart their mass to the parent-part that they're attached to.](http://www.reddit.com/r/KerbalSpaceProgram/comments/34bjk1/)

If this is the case, attaching a physicsless part to the side of something should increase it's mass, but not induce any torque. Yet KER seems to be assuming torque would occur:

![screenshot of example](http://i.imgur.com/hyjfgvW.png)

The issue is discussed [here in the KER forum.](http://forum.kerbalspaceprogram.com/threads/18230-1-0-2-Kerbal-Engineer-Redux-v1-0-16-6?p=1897622&viewfull=1#post1897622)

**Comment by Gerry1135** [comment]
Yes, this does appear to be a bug.  The mass is correctly added to the parent part but the mass is still applied through the part's own COM in the torque calculations rather than being applied through the parent's COM.

There is a debug option to control various aspects of physicsless parts and the code should really honour the setting of these controls.

**Comment by Gerry1135** [comment]
I have done a simple fix for this issue in PR #29 
It now correctly applies the mass to the parent part so the torque calculations work correctly

**Comment by CYBUTEK** [comment]
#29 has been merged.
